# Global settings
global:
  storageClass: "standard"

# ClickHouse Keeper settings
keeper:
  enabled: true
  replicasCount: 3
  storage:
    class: ""  # Defaults to global.storageClass if empty
    size: "5Gi"
  image:
    repository: "altinity/clickhouse-keeper"
    tag: "25.8.12.20747.altinityantalya"
    pullPolicy: "IfNotPresent"

# ClickHouse Vector settings
vector:
  enabled: true
  shardsCount: 1
  replicas:
    count: 1
    storage:
      class: ""  # Defaults to global.storageClass if empty
      size: "10Gi"
    nodeSelector:
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "clickhouse"
        effect: "NoSchedule"
  image:
    repository: "altinity/clickhouse-server"
    tag: "25.8.12.20747.altinityantalya"

# ClickHouse Swarm settings
swarm:
  enabled: true
  shardsCount: 1
  replicas:
    count: 1
    storage:
      class: ""  # Defaults to global.storageClass if empty
      size: "10Gi"
    nodeSelector:
    tolerations:
      - key: "antalya"
        operator: "Equal"
        value: "swarm"
        effect: "NoSchedule"
      - key: "dedicated"
        operator: "Equal"
        value: "clickhouse"
        effect: "NoSchedule"
    affinity:
  image:
    repository: "altinity/clickhouse-server"
    tag: "25.8.12.20747.altinityantalya"

# Ice Rest Catalog settings
iceRestCatalog:
  catalogBucket: warehouse
  s3:
    endpoint: "http://minio:9000"
    accessKeyID: minio
    secretAccessKey: minio123
    region: minio
  storage:
    class: "" # Defaults to global.storageClass if empty

# etcd settings
etcd:
  storage:
    class: "" # Defaults to global.storageClass if empty

minio:
  enabled: true
  rootUser: minio
  rootPassword: minio123
  awsRegion: minio
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2025-03-12T18-04-18Z
  replicas: 1
